name: Deploy to Linux Server

on:
  push:
    branches:
      - ci-cd  # Deploy when code is pushed to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

       # Add the .env file
      - name: Add .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      # Set up Docker Buildx (if multi-platform builds are needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t daivinod/test.analytics.aboss.in:latest .

      # Push the Docker image to DockerHub
      - name: Push Docker image
        run: |
          docker push daivinod/test.analytics.aboss.in:latest

      # Deploy to the Linux server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          password: ${{ secrets.SERVER_PASSWORD }} 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}          
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Pull the latest Docker image
            docker pull daivinod/test.analytics.aboss.in:latest
            
            # Stop and remove the existing container (if any)
            docker stop test.analytics || true
            docker rm test.analytics || true
            
            # Run the container with the new image
            docker run --platform linux/amd64 -d -p 4173:4173 --name analytics --restart always daivinod/test.analytics.aboss.in:latest
            docker image prune -a -f
