name: Deploy to Linux Server

on:
  push:
    branches:
      - main  # Deploy when code is pushed to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

       # Add the .env file
      - name: Add .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      # Set up Docker Buildx (if multi-platform builds are needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ajithantony/test:v1.0 .

      # Push the Docker image to DockerHub
      - name: Push Docker image
        run: |
          docker push ajithantony/test:v1.0

      # Deploy to the Linux server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          password: ${{ secrets.SERVER_PASSWORD }} 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}          
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Pull the latest Docker image
            docker pull ajithantony/test:v1.0
            
            # Stop and remove the existing container (if any)
            docker stop test|| true
            docker rm test|| true
            
            # Run the container with the new image
            docker run  -d -p 3001:3001 --name test --restart always ajithantony/test:v1.0
            docker image prune -a -f
